package sijimpitGUI;

import java.sql.*;
import javax.swing.*;
import java.util.Timer;
import java.util.TimerTask;

public class MenungguKonfirmasiAdmin extends javax.swing.JFrame {
    private String nik;

    /**
     * Creates new form MenungguKonfirmasiAdmin
     */
     public MenungguKonfirmasiAdmin(String nikUser) {
        this.nik = nikUser; // Simpan NIK yang diterima
        initComponents();
        startStatusCheck();
        this.setLocationRelativeTo(null); // Center the window
        jProgressBar1.setIndeterminate(true); // Make progress bar animate
    }

<<<<<<< HEAD
    MenungguKonfirmasiAdmin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
=======
    public MenungguKonfirmasiAdmin() {
    // Tambahkan inisialisasi GUI atau logika lain di sini
    initComponents(); // jika Anda pakai NetBeans GUI Builder
}
>>>>>>> 26f4276de6611404242b06ba88c42b5ccfcdcf4f
    private void startStatusCheck() {
    Timer timer = new Timer();
    timer.schedule(new TimerTask() {
        @Override
        public void run() {
<<<<<<< HEAD
=======
            
>>>>>>> 26f4276de6611404242b06ba88c42b5ccfcdcf4f
            try {
                // Ganti sesuai dengan koneksi database kamu
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/sijimpit", "root", "");
                Statement stmt = conn.createStatement();

                // Misal kamu ingin mengecek berdasarkan NIK pengguna tertentu
                String nikPengguna = nik; // HARUS dinamis nanti
                String sql = "SELECT status FROM menu_pembayaran_warga WHERE nik='" + nikPengguna + "' ORDER BY tanggal DESC LIMIT 1";
                ResultSet rs = stmt.executeQuery(sql);

                if (rs.next()) {
                    String status = rs.getString("status");
                    if ("terbayar".equalsIgnoreCase(status)) {
                        timer.cancel(); // stop pengecekan
                        SwingUtilities.invokeLater(() -> {
                            dispose(); // tutup jendela ini
                            new PembayaranBerhasil().setVisible(true); // tampilkan jendela sukses
                        });
                    }
                }

                rs.close();
                stmt.close();
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }, 0, 5000); // cek setiap 5 detik
}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sijimpitGUI/SijimpitIcon/sand-clock.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Menunggu Konfirmasi dari Admin");

        jProgressBar1.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public static void main(String args[]) {
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
